config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user, :foreign_key => 'user_id', :class_name => 'User'
    belongs_to :user, :foreign_key => 'friend_id', :class_name => 'User'

    after_create :create_inverse_friendship

    def create_inverse_friendship
        # if the inverse bi-directional association doesn't exist, create it
        if Friendship.where(user_id: self.friend_id, friend_id: self.user_id).empty?
            Friendship.create(user_id: self.friend_id, friend_id: self.user_id)
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :friendships, class_name: 'Friendship', dependent: :destroy
    has_many :friends, through: :friendships, source: :user

    after_create :fetch_profile, if: :valid_personal_website?
    before_save :generate_short_url, if: (:will_save_change_to_personal_website? && :valid_personal_website?)

    def query_profiles(text)
        # safe from sql injection
        users = User.where('UPPER(profile) like ?', "%#{text.upcase}%").pluck(:id, :profile)
        results = []
        users.each do |user_id, match|
            next if user_id == self.id
            results.push({match => determine_friendship(self.id, user_id)})
        end
        results
    end

    def determine_friendship(a, b)
        source = User.find(a)
        dest = User.find(b)
        # check if already friends
        source_friends = source.friends.pluck(:id).sort
        return [source.name, dest.name] if source_friends.include?(b)

        # check if mutual friends
        dest_friends = dest.friends.pluck(:id).sort
        common_friends = source_friends & dest_friends

        return [source.name, User.find(common_friends.first).name, dest.name] unless common_friends.empty?

        # else, we need to process more friends
        source_traversal = [[a], source_friends]
        dest_traversal = [[b], dest_friends]

        return find_mutual_friends(source_friends, dest_friends, source_traversal, dest_traversal)
    end
    
    def find_mutual_friends(source_friends, dest_friends, source_traversal, dest_traversal)
        # let's start by processing the smaller list for friends, first
        # we want to get the friends of the friends in the friendlist and then check for common friends with the other list
        if source_friends.length > dest_friends.length
            new_dest_friends = Friendship.where(user_id: dest_friends).distinct.pluck(:friend_id).sort
            dest_friends = new_dest_friends.difference(dest_traversal.flatten)
            dest_traversal.push(dest_friends) unless dest_friends.empty?
        else
            new_source_friends = Friendship.where(user_id: source_friends).distinct.pluck(:friend_id).sort
            source_friends = new_source_friends.difference(source_traversal.flatten)
            source_traversal.push(source_friends) unless source_friends.empty?
        end

        # if we grab more friends of friends and remove already processed and it comes back empty, 
        # we've reached the extent of the friend network
        return if dest_friends.empty? || source_friends.empty? 

        # check if we have any mutual friends
        common_friends = (dest_friends & source_friends).sort

        unless common_friends.empty?
            common_friend = common_friends.first
            source = process_friends_list(source_traversal, common_friend)
            dest = process_friends_list(dest_traversal, common_friend)

            return (source + dest.reverse).uniq
        end

        # update the list of friends we already processed
        
        find_mutual_friends(source_friends, dest_friends, source_traversal, dest_traversal)
    end

    def process_friends_list(list, common)
        last_item = list.pop

        # grab the friends of the common friend and look for common friends within the last_item
        common_friend = User.find(common)
        friends = User.find(common).friends.pluck(:id).sort

        next_common_friend = (list.last & friends).first

        if list.length == 1
            final_node = list.pop.pop
            return [User.find(final_node).name, common_friend.name]
        else
            return process_friends_list(list, next_common_friend) + [common_friend.name]
        end
    end

    def fetch_profile
        require 'open-uri'

        doc = Nokogiri::HTML.parse(self.personal_website)
        headers = doc.css('h1, h2, h3').map(&:text).join("\n")

        self.update(profile: headers)
    end

    def generate_short_url
        # generic oauth token
        # 6c8820b32649fe8b9f89d7c155f73b7d2f5dd27c
        client = Bitly::API::Client.new(token: '6c8820b32649fe8b9f89d7c155f73b7d2f5dd27c')
        url = client.shorten(long_url: self.personal_website)

        self.shortened_url = url.link
    end

    def valid_personal_website?
        uri = URI.parse(self.personal_website)
        uri.is_a?(URI::HTTP) && !uri.host.nil?
    rescue URI::InvalidURIError
        false
    end

    def friend_count
        self.friends.count
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(id: params[:id])
    unless params[:search].blank?
      @results = @user.query_profiles(params[:search])
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @all_users = User.all
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by(id: params[:id])
    # remove self from list of all users
    @all_users = User.all - [@user]
    @user_friends = @user.friendships.build
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    params[:friendship][:friend_id].each do |friend_id|
      if !friend_id.empty?
        @user.friendships.build(:friend_id => friend_id)
      end
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params[:friendship][:friend_id].each do |friend_id|
      if !friend_id.empty?
        @user.friendships.build(:friend_id => friend_id)
      end
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :personal_website, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %> <br />
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :personal_website %> <br />
    <%= form.text_field :personal_website %>
  </div>
  <%= fields_for(@user_friends) do |friend| %>
    <div class="field">
      <%= friend.label "All Friends" %><br />
      <%= collection_select(:friendship, :friend_id, @all_users, :id, :name, { :selected => @user.friendships.pluck(:friend_id) }, {:multiple => true})%>
    </div>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">Name</th>
      <th colspan="2">Short URL</th>
      <th colspan="1">Number of Friends</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.shortened_url %></td>
        <td><%= user.friend_count%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th colspan="2">Name</th>
      <th colspan="2">Short URL</th>
      <th colspan="3">Friends</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td colspan="2"><%= @user.name %></td>
      <td colspan="2"><%= @user.shortened_url %></td>
      <td colspan="3"><%= @user.friends.pluck(:name).join(", ")%></td>
    </tr>
  </tbody>
</table>

<%= form_tag(user_path(@user.id), method: :get) do %>
    <div class="input-group">
        <%= text_field_tag(:search, params[:search], placeholder: "Search") %>
        <div class="input-group-btn">
            <%= button_tag "search", :name => nil%>
        </div>
    </div>
<% end %>
<% if @results %>
  <% @results.each do |result| %>
     <% result.each do |match_text, friends| %>
        <%= friends.join("->") %>(<%= match_text%>)<br />
     <% end %>
  <% end %>
<% elsif @results.nil? && params[:search] %>
  No search results found for <%= params[:search] %><br />
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>